name: Validate .NET solution
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * 2'
jobs:
  validate-dotnet:
    name: Validate .NET solution
    uses: azure-samples/code-validation/.github/workflows/dotnet.yml@main
    with:
      version: '8.0'
      working-directory: './src'