name: Validate .NET solution
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '23 4 * * 5'
jobs:
  dotnet-format:
    name: Check code formatting
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check .NET version
        run: dotnet --version
      - name: Check .NET code format
        run: dotnet format --verify-no-changes
        working-directory: ./src
